id: AA099D23B
title: Supplement to the Omniscient Ngorchen Kunga Zangpo’s Prayer to the Lineage
  of Parting from the Four Attachments
type: translation
pechas:
- I01166F21
- I29E40090
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:33:36.796911
  last_modified_at: 2023-01-04 12:33:36.796940
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I01166F21/B498: B1BE
  I29E40090/8A74: B1BE
